words = [
    "berr",
    "bitness",
    "cstr",
    "dosexec",
    "dyn",
    "dynsym",
    "ehdr",
    "endiannes",
    "ent",
    "errno",
    "getopt",
    "interp",
    "libmagic",
    "libncurses",
    "lifecycle",
    "mmap",
    "msfconsole",
    "ndx",
    "osabi",
    "phdr",
    "phdrs",
    "phnum",
    "readelf",
    "rela",
    "runpath",
    "sharedlib",
    "shdr",
    "shdrs",
    "shnum",
    "shstrtab",
    "siz",
    "soname",
    "strdup",
    "strtab",
    "syms",
    "symtab",
    "und",
    "unmmap",
    "virt",
]
