words = [
    "alphamosaic",
    "atmel",
    "avr",
    "berr",
    "berror",
    "bitness",
    "bitstring",
    "blackfin",
    "cnt",
    "coldfire",
    "cris",
    "cstr",
    "denso",
    "dosexec",
    "dsp",
    "dyn",
    "dynstr",
    "dynsym",
    "ehdr",
    "endiannes",
    "ent",
    "entsize",
    "errno",
    "getopt",
    "gpp",
    "hppa",
    "huany",
    "infineon",
    "interp",
    "libmagic",
    "libncurses",
    "lifecycle",
    "lsi",
    "matsushita",
    "mcu",
    "mma",
    "mmap",
    "mmix",
    "msfconsole",
    "ndr",
    "ndx",
    "nec",
    "nhdr",
    "osabi",
    "pdp",
    "phdr",
    "phdrs",
    "phent",
    "phentsize",
    "phnum",
    "pico",
    "rce",
    "readelf",
    "rela",
    "relatab",
    "reloc",
    "relocations",
    "relocs",
    "relr",
    "relrtab",
    "reltab",
    "runpath",
    "sharedlib",
    "shdr",
    "shdrs",
    "shent",
    "shentsize",
    "shnum",
    "shstrtab",
    "sht",
    "siz",
    "snp",
    "soname",
    "spu",
    "strdup",
    "strtab",
    "syms",
    "symtab",
    "tensilica",
    "tera",
    "tpc",
    "trebia",
    "tricore",
    "trw",
    "ubicom",
    "und",
    "unmmap",
    "vaddr",
    "ver",
    "verdaux",
    "verdef",
    "vernaux",
    "verneed",
    "versym",
    "virt",
    "vpp",
    "xtensa",
    "zsp",
]
