words = [
    "binsight",
    "bitness",
    "calloc",
    "cflags",
    "cmake",
    "ehdr",
    "ent",
    "hdr",
    "libmagic",
    "libncurses",
    "nident",
    "osabi",
    "phdr",
    "phdrs",
    "phnum",
    "relocations",
    "relro",
    "relwithdebinfo",
    "rwx",
    "shdr",
    "shdrs",
    "shnum",
    "shstrndx",
    "shstrtab",
    "siz",
    "virt",
    "wextra",
    "wpedantic",
]
