words = [
    "berr",
    "berror",
    "binsight",
    "bitness",
    "calloc",
    "cflags",
    "cmake",
    "dosexec",
    "dyn",
    "dynstr",
    "dynsym",
    "dynsymdx",
    "dynsymndx",
    "ehdr",
    "elfclass",
    "elfosabi",
    "ent",
    "entsize",
    "eprint",
    "errno",
    "filesz",
    "getopt",
    "hdr",
    "hios",
    "interp",
    "libmagic",
    "libncurses",
    "memsz",
    "mmap",
    "munmap",
    "ndx",
    "nident",
    "osabi",
    "paddr",
    "phdr",
    "phdrs",
    "phentsize",
    "phnum",
    "phoff",
    "portexec",
    "readelf",
    "rela",
    "relocations",
    "relro",
    "relwithdebinfo",
    "rpath",
    "runpath",
    "rwx",
    "sharedlib",
    "shdr",
    "shdrs",
    "shentsize",
    "shnum",
    "shoff",
    "shsize",
    "shstrndx",
    "shstrtab",
    "siz",
    "soname",
    "strdup",
    "strtab",
    "syms",
    "symtab",
    "symtabndx",
    "und",
    "vaddr",
    "verdef",
    "virt",
    "wextra",
    "wpedantic",
]
